# Generated by Django 3.1.4 on 2020-12-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='days',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
